sravani/force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>PositionId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positioins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sravani/force-app/main/default/objects/Position__c/fields/hiringmanger__c.field-meta.xml
<CustomField>
    <fullName>hiringmanger__c</fullName>
    <label>hiringmanger</label>
    <referenceTo>HiringManager__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sravani/force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hyd</fullName>
            </value>
            <value>
                <fullName>Bang</fullName>
            </value>
            <value>
                <fullName>Mas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sravani/force-app/main/default/objects/Position__c/fields/Maxpay__c.field-meta.xml
<CustomField>
    <fullName>Maxpay__c</fullName>
    <label>Maxpay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

sravani/force-app/main/default/objects/Position__c/fields/MilestoneDate__c.field-meta.xml
<CustomField>
    <fullName>MilestoneDate__c</fullName>
    <label>MilestoneDate</label>
    <type>Date</type>
</CustomField>

sravani/force-app/main/default/objects/Position__c/fields/Minpay__c.field-meta.xml
<CustomField>
    <fullName>Minpay__c</fullName>
    <label>Minpay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

sravani/force-app/main/default/objects/Position__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

sravani/force-app/main/default/objects/Position__c/fields/Noofpositions__c.field-meta.xml
<CustomField>
    <fullName>Noofpositions__c</fullName>
    <label>Noofpositions</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sravani/force-app/main/default/objects/Position__c/fields/Position_Status__c.field-meta.xml
<CustomField>
    <fullName>Position_Status__c</fullName>
    <label>Position Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Never Fill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sravani/force-app/main/default/objects/Position__c/fields/PositionDescription__c.field-meta.xml
<CustomField>
    <fullName>PositionDescription__c</fullName>
    <label>PositionDescription</label>
    <type>TextArea</type>
</CustomField>

sravani/force-app/main/default/objects/Position__c/fields/Skillset__c.field-meta.xml
<CustomField>
    <fullName>Skillset__c</fullName>
    <label>Skillset</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>java</fullName>
            </value>
            <value>
                <fullName>dotnet</fullName>
            </value>
            <value>
                <fullName>salesforce</fullName>
            </value>
            <value>
                <fullName>javascript</fullName>
            </value>
            <value>
                <fullName>apex</fullName>
            </value>
            <value>
                <fullName>lwc</fullName>
            </value>
            <value>
                <fullName>integeration</fullName>
            </value>
            <value>
                <fullName>python</fullName>
            </value>
            <value>
                <fullName>php</fullName>
            </value>
            <value>
                <fullName>reactjs</fullName>
            </value>
            <value>
                <fullName>sql</fullName>
            </value>
            <value>
                <fullName>oracle</fullName>
            </value>
            <value>
                <fullName>nodejs</fullName>
            </value>
            <value>
                <fullName>mongodb</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sravani/force-app/main/default/classes/positionHelper.cls
public class positionHelper {
    
    
    public void createposition(Id hmgrrecordid){
        
        Position__c psobj=new Position__c();
        psobj.Name__c='salesforce tester';
        psobj.phone__c='4564646';
        psobj.Location__c='hyd';
        psobj.Skillset__c='salesforce,apex';
        psobj.Position_Status__c='new';
        psobj.PositionDescription__c='requied 5+ years exp in sales and service cloud with lwc,integeraiton and apex';
        psobj.Open_Date__c=system.today();
        psobj.MilestoneDate__c=system.today()+30;
        psobj.Maxpay__c=64646464;
        psobj.Minpay__c=131313;
        psobj.Noofpositions__c=30;
        psobj.hiringmanger__c=hmgrrecordid; 
        if(psobj!=null){
            insert psobj;
            if(psobj.id!=null){
                system.debug(psobj);
            }
        }
    }

}