sravani/force-app/main/default/objects/HiringManager__c/HiringManager__c.object-meta.xml
<CustomObject>
    <label>HiringManager</label>
    <nameField>
        <displayFormat>HMGR-{00000}</displayFormat>
        <label>HiringManagerId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HiringManagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sravani/force-app/main/default/objects/HiringManager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>bangalore</fullName>
            </value>
            <value>
                <fullName>chennai</fullName>
            </value>
            <value>
                <fullName>hyd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sravani/force-app/main/default/objects/HiringManager__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sravani/force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>PositionId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positioins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sravani/force-app/main/default/objects/Position__c/fields/hiringmanger__c.field-meta.xml
<CustomField>
    <fullName>hiringmanger__c</fullName>
    <label>hiringmanger</label>
    <referenceTo>HiringManager__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sravani/force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hyd</fullName>
            </value>
            <value>
                <fullName>Bang</fullName>
            </value>
            <value>
                <fullName>Mas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sravani/force-app/main/default/objects/Position__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

sravani/force-app/main/default/classes/DataForTest.cls
public class DataForTest {
    
    
    public static void createleads(){
        
        List<lead> leadlist=new list<Lead>();
        for(integer i=0;i<=10;i++){
            Lead l=new lead();
            l.LastName='testclasslead'+i;
            l.Phone='1231232';
            l.City='hyd';
            l.Fax='6546987978';
            l.Company='testclasscompany';
            l.Website='www.testclasscompany.com';
            leadlist.add(l);
        }
        insert leadlist;
    }
    
    public static void createaccount(){
        list<Account> accountlist=new list<Account>();
        for(integer i=1;i<=10;i++){
            Account acc=new Account();
            acc.Name='testclassaccount'+i;
            acc.Phone='1234565789';
            acc.BillingCity='hyderabad';
            acc.Industry='energy';
            accountlist.add(acc);
        }
		system.debug(accountlist);
        insert accountlist;
        if(!accountlist.isempty()){
            for(Account acc:accountlist){
                createcontacts(acc.Id);
            }
        }
    }
    
    public static void createcontacts(Id accid){
        list<Contact> conlist=new list<contact>();
        for(integer i=1;i<=5;i++){
            contact con=new contact();
            con.lastname='testclasscontact'+i;
            con.AccountId=accid;
            con.Phone='123445';
            conlist.add(con);
        }
        insert conlist;
    }
    
    public static void createpositions(){
        HiringManager__c hmgr=new HiringManager__c();
        hmgr.name__c='hmgrtestclass';
        hmgr.email__c='hmgrtestclass@gmail.com';
        hmgr.Phone__c='1234567890';
        insert hmgr;
        
        Position__c ps=new Position__c();
        ps.Name__c='testclassposition';
        ps.Location__c='Hyd';
        ps.phone__c='78979879';
        ps.hiringmanger__c=hmgr.Id;
        
        insert ps;
        
    }

}