sravani/force-app/main/default/objects/HiringManager__c/HiringManager__c.object-meta.xml
<CustomObject>
    <label>HiringManager</label>
    <nameField>
        <displayFormat>HMGR-{00000}</displayFormat>
        <label>HiringManagerId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HiringManagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sravani/force-app/main/default/objects/HiringManager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>bangalore</fullName>
            </value>
            <value>
                <fullName>chennai</fullName>
            </value>
            <value>
                <fullName>hyd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sravani/force-app/main/default/objects/HiringManager__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sravani/force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>PositionId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Positioins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sravani/force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hyd</fullName>
            </value>
            <value>
                <fullName>Bang</fullName>
            </value>
            <value>
                <fullName>Mas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sravani/force-app/main/default/objects/Position__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

sravani/force-app/main/default/classes/GlobalSearchUtility.cls
public with sharing class GlobalSearchUtility {
    public GlobalSearchUtility() {

    }

    public static void serachrecords(){
        List<List<Sobject>> searchresults=[FIND 'bulk*' IN ALL FIELDS RETURNING 
                                            Account(id,name,industry,phone),
                                            Contact(id,Lastname,phone,email),
                                            Lead(id,Lastname,firstname,email,company),
                                            Position__c(id,name__c,location__C),
                                            HiringManager__c(id,name__c,phone__c)];

        if(!searchresults.isempty()){
            List<Account> acclist=(List<Account>)searchresults.get(0);
             List<Contact> conlist=(List<Contact>)searchresults.get(1);
             List<Lead> leadlist=(List<Lead>)searchresults.get(2);
             List<Position__c> poslist=(List<Position__c>)searchresults.get(3);
             List<HiringManager__c> hmgrlist=(List<hiringmanager__C>)searchresults.get(4);
            for(List<Sobject> listobj:searchresults){
                system.debug(listobj);
            }
            for(Account accobj:acclist){
                system.debug(accobj);
            }
            for(Contact conobj:conlist){
                system.debug(conobj);
            }
            system.debug('hiring amanger');
            for(hiringmanager__C  hmgr:hmgrlist){
                system.debug(hmgr);
            }
            
        }
    }


    public static void dynamicsearch(String serachstring){
        String searchquery='FIND \''+serachstring+ '*\' IN ALL FIELDS RETURNING '+
                            'Account(id,name,industry,phone),'+
                            'Contact(id,name,phone,email),'+
                            'Lead(id,name,firstname,email,company),'+
                            'Position__c(id,name__c,location__C),'+
                            'HiringManager__c(id,name__c,phone__c)';
        
        
        List<List<Sobject>> searchresults=search.query(searchquery);

        if(!searchresults.isempty()){
            List<Account> acclist=(List<Account>)searchresults.get(0);
             List<Contact> conlist=(List<Contact>)searchresults.get(1);
             List<Lead> leadlist=(List<Lead>)searchresults.get(2);
             List<Position__c> poslist=(List<Position__c>)searchresults.get(3);
             List<HiringManager__c> hmgrlist=(List<hiringmanager__C>)searchresults.get(4);


            for(List<Sobject> listobj:searchresults){
                system.debug(listobj);
            }

            for(Account accobj:acclist){
                system.debug(accobj);
            }

             for(Contact conobj:conlist){
                 system.debug(conobj);
             }
             for(Lead leadobj:leadlist){
                 system.debug(leadobj);
             }

              for(Position__c posobj:poslist){
                  system.debug(posobj);
              }

              for(HiringManager__c hmgr:hmgrlist){
                  system.debug(hmgr);
              }
              
        }       

    }
}